[package]
name = "isometric_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wfc_voxel = "0.1.0"
bevy = "0.10.1"
rand = "0.8.5"